Web/src/Entity/ContactAdmin.php
<?php
namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

class ContactAdmin{



    /**
     * @var string|null
     * @Assert\NotBlank()
     * @Assert\Length(min=2, max=100)
     */
    private $firstname;



    /**
     * @var string|null
     * @Assert\NotBlank()
     * @Assert\Length(min=2, max=100)
     */
    private $Lastname;



    /**
     * @var string|null
     * @Assert\NotBlank()
     * @Assert\Length(min=2, max=100)
     */
    private $Equipe;

    /**
     * @return string|null
     */
    public function getEquipe(): ?string
    {
        return $this->Equipe;
    }

    /**
     * @param string|null $Equipe
     * @return ContactAdmin
     */
    public function setEquipe(?string $Equipe): ContactAdmin
    {
        $this->Equipe = $Equipe;
        return $this;
    }


    /**
     * @var string|null
     * @Assert\NotBlank()
     *
     */
    private $phone;


    /**
     * @var string|null
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $Email;



    /**
     * @var string|null
     * @Assert\NotBlank()
     * @Assert\Length (min=10)
     */
    private $message;

    /**
     * @var Competition|null

     */
    private $Competition;

    /**
     * @return Competition|null
     */
    public function getCompetition(): ?Competition
    {
        return $this->Competition;
    }

    /**
     * @param Competition|null $Competition
     * @return ContactAdmin
     */
    public function setCompetition(?Competition $Competition): ContactAdmin
    {
        $this->Competition = $Competition;
        return $this;
    }



    /**
     * @return string|null
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    /**
     * @param string|null $firstname
     * @return ContactAdmin
     */
    public function setFirstname(?string $firstname): ContactAdmin
    {
        $this->firstname = $firstname;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    /**
     * @param string|null $Lastname
     * @return ContactAdmin
     */
    public function setLastname(?string $Lastname): ContactAdmin
    {
        $this->Lastname = $Lastname;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * @param string|null $phone
     * @return ContactAdmin
     */
    public function setPhone(?string $phone): ContactAdmin
    {
        $this->phone = $phone;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->Email;
    }

    /**
     * @param string|null $Email
     * @return ContactAdmin
     */
    public function setEmail(?string $Email): ContactAdmin
    {
        $this->Email = $Email;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * @param string|null $message
     * @return ContactAdmin
     */
    public function setMessage(?string $message): ContactAdmin
    {
        $this->message = $message;
        return $this;
    }



}

Web/templates/front/competition.html.twig
{% extends'front/base.html.twig' %}
{% block title %} competition
{% endblock %}
{% block body %}
    <div class="kode-subheader subheader-height">
        <div class="container">
            <div class="row">

            </div>
        </div>
    </div>
    <div class="kode-content">
    <h1>Liste des Competition</h1>

    <table border="1" width="90%" align="center">



        <tr >
            <th>desgniation</th> <th>ddd</th><th>neeq</th><th>categorie</th><th>prix</th>

        </tr>




        <tr {% for c in Competition %}  >

            <td>{{ c.designation }}</td>

            <td>{{ c.dateDebut.format('d/m/Y') }}</td>
            <td>{{ c.nbreEquipes }}</td>
            <td>{{ c.categorie.getDesignation() }}</td>

            <td>{{ c.prixParticipation }}</td>


            <td style="display: inline-block">

                <form >

                    <a href="{{ path ('participe', {'id':c.id}) }}" class="btn btn-success" >Participe</a>
                </form>
            </td>
        </tr {% endfor %} >

    </table>




{% endblock%}

Web/templates/front/contactus.html.twig
{% extends'front/base.html.twig' %}
{% block title %} Contact US
{% endblock %}
{% block body %}
    <div class="kode-subheader subheader-height">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>Contact Us</h1>
                </div>
                <div class="col-md-6">
                    <ul class="kode-breadcrumb">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--// SubHeader //-->

    <!--// Main Content //-->
    <div class="kode-content">

        <!--// Page Content //-->
        <section class="kode-pagesection">
            <div class="container">
                <div class="row">

                    <div class="kode-pagecontent col-md-12">
                        <div class="kode-map">
                            <div class="map-canvas" id="map-canvas"></div>
                        </div>

                        <div class="contactus-page">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="kode-simple-form">
                                        <form method="post" class="comments-form" id="contactform">
                                            <ul>
                                                <li><input type="text" id="name" name="name" class="required" placeholder="Name *"></li>
                                                <li><input type="text" id="email" name="email" class="required email" placeholder="Email *"></li>
                                                <li><input type="text" name="address" id="address" placeholder="Address:"></li>
                                                <li><textarea name="message" id="message" placeholder="add your message"></textarea></li>
                                                <li>
                                                    <label for="verify">Are you human?</label>
                                                    <iframe src="inc/capcha_page.html" height="29" width="80" scrolling="no" frameborder="0" marginheight="0" marginwidth="0" class="capcha_image_frame" name="capcha_image_frame"></iframe>
                                                    <input class="verify" type="text" id="verify" name="verify" />
                                                </li>
                                                <li><input class="thbg-color" type="submit" value="send"></li>
                                            </ul>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="kode-section-title"> <h2>Contact Info</h2> </div>
                                    <div class="kode-forminfo">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip..</p>
                                        <ul class="kode-form-list">
                                            <li><i class="fa fa-home"></i> <p><strong>Address:</strong> 805 omnis iste natus error sit voluptatem accusantium</p></li>
                                            <li><i class="fa fa-phone"></i> <p><strong>Phone:</strong> 111 8756 22  777 4456 112</p></li>
                                            <li><i class="fa fa-envelope-o"></i> <p><strong>Email:</strong> Info@sportyleague.com</p></li>
                                        </ul>
                                        <h3>Find Us On</h3>
                                        <ul class="kode-team-network">
                                            <li><a href="#" class="fa fa-facebook"></a></li>
                                            <li><a href="#" class="fa fa-twitter"></a></li>
                                            <li><a href="#" class="fa fa-linkedin"></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </section>
        <!--// Page Content //-->

    </div>
{% endblock%}

Web/templates/front/fixture.html.twig
{% extends'front/base.html.twig' %}
{% block title %} fixture
{% endblock %}
{% block body %}
    <div class="kode-subheader subheader-height">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>Fixture</h1>
                </div>
                <div class="col-md-6">
                    <ul class="kode-breadcrumb">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--// SubHeader //-->

    <!--// Main Content //-->
    <div class="kode-content">

        <!--// Page Content //-->
        <section class="kode-pagesection margin-bottom-40">
            <div class="container">
                <div class="row">
                    <div class="kode-pagecontent col-md-8">

                        <div class="kode-inner-fixer margin-none padding-none">
                            <div class="kode-fixer-counter">
                                <h2 class="thbg-color">Next Match Started In</h2>
                                <div id="kodeCountdown"></div>
                            </div>
                            <div class="kode-team-match">
                                <ul>
                                    <li><a href="#"><img src="{{ asset('fonts/extra-images/fixer-logo1.png') }}" alt=""></a></li>
                                    <li class="home-kode-vs"><a href="#" class="kode-modren-btn thbg-colortwo">vs</a></li>
                                    <li><a href="#"><img src="{{ asset('fonts/extra-images/fixer-logo2.png') }}" alt=""></a></li>
                                </ul>
                                <div class="clearfix"></div>
                                <span class="kode-subtitle">Cycle Racing, Hockey May 18, 2015 14:30 - 16:00 CAMBRIDGESHIRE-UK</span>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-4">
                        <table class="kode-table kode-table-v2">
                            <thead>
                            <tr>
                                <th>Team</th>
                                <th>w</th>
                                <th>d</th>
                                <th>l</th>
                                <th>pts</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Chelsea</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Aresenal</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Real Soccer</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Real Madrid</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>City Club</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Aresenal</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Real Soccer</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Real Madrid</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Aresenal</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Aresenal</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Real Soccer</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            <tr>
                                <td>Real Madrid</td>
                                <td>11</td>
                                <td>02</td>
                                <td>00</td>
                                <td>42</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="col-md-12">
                        <div class="kode-section-title"> <h2>Upcoming Fixture In May 2015</h2> </div>
                        <div class="kode-fixer-list">
                            <ul class="table-head thbg-color">
                                <li><h5>Upcoming Match</h5></li>
                                <li> <h5>Date & TIme</h5> </li>
                                <li> <h5>Venue</h5> </li>
                                <li class="fixer-pagination"> <a href="#" class="fa fa-angle-right"></a> <a href="#" class="fa fa-angle-left"></a> </li>
                            </ul>
                            <ul class="table-body">
                                <li>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo3.png') }}" alt=""> Aresenal</a>
                                    <span>vs</span>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo4.png') }}" alt=""> FC Bayern</a>
                                </li>
                                <li><small>18/05/2015  14:30 - 16:00</small></li>
                                <li><small>Wembley Stadium</small></li>
                                <li class="fixer-btn">
                                    <a href="#">Match Report</a>
                                    <a href="#">Buy A Ticket</a>
                                </li>
                            </ul>
                            <ul class="table-body">
                                <li>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo3.png') }}" alt=""> Perspiciatis</a>
                                    <span>vs</span>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo4.png') }}" alt=""> Chelse</a>
                                </li>
                                <li><small>18/05/2015  14:30 - 16:00</small></li>
                                <li><small>Wembley Stadium</small></li>
                                <li class="fixer-btn">
                                    <a href="#">Match Report</a>
                                    <a href="#">Buy A Ticket</a>
                                </li>
                            </ul>
                            <ul class="table-body">
                                <li>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo3.png') }}" alt=""> Aresenal</a>
                                    <span>vs</span>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo4.png') }}" alt=""> FC Bayern</a>
                                </li>
                                <li><small>18/05/2015  14:30 - 16:00</small></li>
                                <li><small>Wembley Stadium</small></li>
                                <li class="fixer-btn">
                                    <a href="#">Match Report</a>
                                    <a href="#">Buy A Ticket</a>
                                </li>
                            </ul>
                            <ul class="table-body">
                                <li>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo3.png') }}" alt=""> Aresenal</a>
                                    <span>vs</span>
                                    <a href="#" class="list-thumb"><img src="{{ asset('fonts/extra-images/fixer-logo4.png') }}" alt=""> FC Bayern</a>
                                </li>
                                <li><small>18/05/2015  14:30 - 16:00</small></li>
                                <li><small>Wembley Stadium</small></li>
                                <li class="fixer-btn">
                                    <a href="#">Match Report</a>
                                    <a href="#">Buy A Ticket</a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        <!--// Page Content //-->

    </div>
    <!--// Main Content //-->

{% endblock %}

Web/templates/front/formparticiper.html.twig
{% extends 'front/base.html.twig' %}

{% block body %}
    <div><br><br><br><br><br><br><br><br><br><br><h1>Demande du participation</h1></div>
<div class="col-md-6" >
{{ form_start(form) }}

    <div>
        <div class="col">{{ form_row(form.firstname) }}</div>
        <div class="col">{{ form_row(form.Lastname) }}</div>

    </div>
    <div>
        <div class="col">{{ form_row(form.phone) }}</div>
        <div class="col">{{ form_row(form.email) }}</div>
        <div class="col">{{ form_row(form.equipe) }}</div>

    </div>
    {{ form_rest(form) }}
    <div>
        <button class="btn btn-primary"> Envoyee</button>

    </div>
    {{ form_end(form) }}
</div>{% endblock %}

Web/templates/front/prticiper.html.twig
{% extends 'front/base.html.twig' %}

{% block body %}
    <section class="container align-content-center mt-5" style="margin-top: 20px">
        {{ include('front/formparticiper.html.twig') }}
    </section>
{% endblock %}

Web/templates/front/reservation.html.twig
{% extends'front/base.html.twig' %}
{% block title %} Invitations
{% endblock %}
{% block style %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
{% endblock %}
{% block body %}

    <div class="kode-subheader subheader-height">
        <div class="container">
            <div class="row">
                <div class="col-md-6">

                </div>
            </div>
        </div>
    </div>

    <div class="container">

                    {% for r in reservations %}
                        <div class="card">

                            {% if r.getAcceptee()==1 %}
                                <h5 class="card-header">Réservation</h5>
                            {% else %}
                                <h5 class="card-header">Invitation</h5>
                            {% endif %}
                            <div class="card-body">
                                <div class="col-md-9">
                                    <h5 class="card-title"><b>Créée par</b> {{ r.getClient().getNom() }} {{ r.getClient().getPrenom() }}</h5>
                                    <p class="card-text"><b>{{ r.getClient().getNom() }} {{ r.getClient().getPrenom() }}</b> a créé une
                                        {% if r.getAcceptee()==1 %}
                                            Réservation
                                        {% else %}
                                            Invitation
                                        {% endif %}
                                        pour un match le <b>{{ r.getDateReservation()|date('d/m/Y') }}</b>  à  <b>{{ r.getHeure()|date('h:m') }}</b>
                                        au <b><a href=""> {{ r.getTerrain().getDesignation() }}</a></b>
                                    </p>
                                    {% if r.getAcceptee()==0 %}
                                        <a href="{{ path ('acceptation', {'id':r.id}) }}') }}" class="btn btn-primary">Accepter</a>
                                        <a href="{{ path ('refus', {'id':r.id}) }}') }}" class="btn btn-primary">Réfuser</a>
                                    {% endif %}
                                </div>
                                <div class="col-md-3">
                                    <a href="{{ path ('invit', {'id':r.id}) }}"> <img src="{{ asset('uploads/terrains/' ~r.getTerrain().getImage()) }}"
                                         style="width: 180px; height: 100px; border-radius: 10%"></a>
                                </div>
                            </div>


                        </div>
                        <br>
                    {% endfor %}
    </div>




{% endblock %}

Web/templates/front/terrain.html.twig
{% extends'front/base.html.twig' %}
{% block title %} terrain
{% endblock %}
{% block body %}

    <div class="kode-subheader subheader-height">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <form method="post">
                        <input type="text" id="search" class="form-control" name="search" placeholder="Recherche" style="width: 300px; color: #0d66c2">
                        <button type="submit" value="" class="btn search">Chercher</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--// SubHeader //-->

    <!--// Main Content //-->
    <div id="cat" class="kode-content">
        {% for message in app.flashes('success')%}

            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor%}
        <!--// Page Content //-->
        <section class="kode-pagesection">
            <div class="container">
                <div class="row">

                    <div class="kode-pagecontent col-md-12">

                        <div class="kode-gallery">
                            <ul class="row">
                                {% for t in terrains %}
                                <li class="col-md-4">
                                    <a href="{{ path ('show_t', {'id':t.id}) }}"><img src="{{ asset('uploads/terrains/' ~t.image) }}" alt=""
                                                                                            style="width: 400px; height: 250px; border-radius: 20px"></a>

                                </li>
                                {% endfor %}




                            </ul>
                            <!--// Pagination //-->
                            <div class="pagination">
                                <a href="#"><i class="fa fa-angle-double-left"></i></a>
                                <a href="#">1</a>
                                <a href="#">2</a>
                                <span>3</span>
                                <a href="#">4</a>
                                <a href="#"><i class="fa fa-angle-double-right"></i></a>
                            </div>
                            <!--// Pagination //-->
                        </div>

                    </div>

                </div>
            </div>
        </section>
        <!--// Page Content //-->

    </div>
    <!--// Main Content //-->


    <!-- /row -->

    <!-- /MAIN CONTENT -->
    <!--main content end-->






{% endblock%}